<a href="https://colab.research.google.com/github/Vedika-Garg/unit1.ipynb/blob/main/Python-project-by-Vedika-Garg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

#finding empty spapces
def find_empty_space(num):
    for Row in range(9):
        for Col in range(9):
            if num[Row][Col] == 0:
                return Row,Col
    return None, None


# guessing the numbers
def is_guess_correct(num, guess, row, col):
    row_val = num[row]
    if guess in row_val:
        return False

    col_val = [num[i][col] for i in range(9)]
    if guess in col_val:
        return False
    square_check_row = (row // 3) * 3
    square_check_col = (col // 3) * 3

    for Row in range(square_check_row, square_check_row + 3):
        for Col in range(square_check_col, square_check_col + 3):
            if num[Row][Col] == guess:
                return False
    return True


#main function of solving game
def sudoku_solver(num):
    row, col = find_empty_space(num)

    if row is None:
        return True

    for guess in range(1,10):
        if is_guess_correct(num, guess, row, col):
            num[row][col] = guess
            if sudoku_solver(num):
                return True

        num[row][col] = 0
    return False



#test sample

example = np.array([
        [0,0,0,    8,0,0,    0,0,9],
        [0,1,9,    0,0,5,    8,3,0],
        [0,4,3,    0,1,0,    0,0,7],


        [4,0,0,    1,5,0,    0,0,3],
        [0,0,2,    7,0,4,    0,1,0],
        [0,8,0,    0,9,0,    6,0,0],


        [0,7,0,    0,0,6,    3,0,0],
        [0,3,0,    0,7,0,    0,8,0],
        [9,0,4,    5,0,0,    0,0,1],
    ])
print(sudoku_solver(example))
print(example)

True
[[2 5 6 8 3 7 1 4 9]
 [7 1 9 2 4 5 8 3 6]
 [8 4 3 6 1 9 2 5 7]
 [4 6 7 1 5 8 9 2 3]
 [3 9 2 7 6 4 5 1 8]
 [5 8 1 3 9 2 6 7 4]
 [1 7 8 4 2 6 3 9 5]
 [6 3 5 9 7 1 4 8 2]
 [9 2 4 5 8 3 7 6 1]]
